import type { NextPage } from 'next';
import Head from 'next/head';
import Header from '../src/components/Header/Header';
import PageWrapper from '../src/components/PageWrapper/PageWrapper';
import styles from '../styles/Home.module.css';
import WeatherData from '../src/components/WeatherData/WeatherData';
import { SearchBar } from '../src/components/SearchBar/SearchBar';
import { useSelector } from 'react-redux';
import { RootState } from '../src/store/store';
import SearchedLocation from '../src/components/SearchedLocation/SearchedLocation';

const Home: NextPage = () => {
    // const cityToLonLat = async () => {};

    // useEffect(() => {
    //     if (generalData) {
    //         setLon(generalData.coord.lon);
    //         setLat(generalData.coord.lat);
    //     }
    // }, [generalData]);

    // useEffect(() => {
    //     if (lat && lon) {
    //         fetch(
    //             `https://api.openweathermap.org/data/2.5/onecall?lat=${lat}&lon=${lon}&exclude=minutely,alerts&appid=${apiKey}`
    //         )
    //             .then((response) => response.json())
    //             .then((data) => setDailyWeatherData(data));
    //     }
    // }, [lat, lon]);

    const weatherData = useSelector(
        (state: RootState) => state.weatherData.weatherData
    );

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <PageWrapper>
                <Header />

                <SearchBar />

                <SearchedLocation />

                <WeatherData />
            </PageWrapper>
        </div>
    );
};

export default Home;
